services:
  postgres:
    container_name: postgres-sql-emp
    image: postgres
    environment:
      POSTGRES_USER: skander
      POSTGRES_PASSWORD: skander12
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: employees
    volumes:
      - postgres:/var/lib/postgresql/data  # Corrected volume mount
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
