services:
  postgres:
    container_name: postgres-sql-emp
    image: postgres
    environment:
      POSTGRES_USER: skander
      POSTGRES_PASSWORD: skander12
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: employees
    volumes:
      - postgres:/var/lib/postgresql/data  # Corrected volume mount
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
